Add Matplotlib visualizations
AndreasPB/aa-mandatory1 pull request #7
Opened 2022-03-06 15:03 UTC by AndreasPB

2022-03-06 16:39 UTC, AndreasPB commented
Waiting for everyone to approve(when they have had it up and running locallly)

2022-03-06 18:32 UTC, nullxDEADBEEF requested changes
Would be awesome to have labels on the y-axis in our visualizations + export them to pdf :DD

2022-03-09 11:41 UTC, Pankai222 commented
:shipit:

2022-03-09 11:56 UTC, Pankai222 commented
Would be awesome to have labels on the y-axis in our visualizations + export them to pdf ;))

2022-03-09 12:11 UTC, Primdahl26 commented
Would be awesome to have labels on the y-axis in our visualizations + export them to pdf :ii

2022-03-09 13:02 UTC, Primdahl26 requested changes, later dismissed
Could we also `poetry add notebook`?

2022-03-09 13:02 UTC, Primdahl26 commented on src/haircut_plots.py
> +df_m.groupby(bins)["Tip amount"].mean().plot.line()
```suggestion
df_m.groupby(bins)["Tip amount"].mean().plot.line().set_ylabel('Tipping amount')
```

2022-03-09 13:02 UTC, Primdahl26 commented on src/haircut_plots.py
> +df_m.groupby("Culture")["Tip amount"].mean().plot.bar(color="orange")
```suggestion
df_m.groupby("Culture")["Tip amount"].mean().plot.bar(color="orange").set_ylabel('Tipping amount')
```

2022-03-09 15:06 UTC, AndreasPB commented
- Dashed/dotted til overlappende grafer
- Skalering af y-værdier(begge skal kunne bruge hele y-aksen(tip/age))
- Få styr på om bar graferne viser hvad du tror

2022-03-11 11:51 UTC, AndreasPB commented on src/haircut_plots.py
> +df_m.groupby(bins)["Tip amount"].mean().plot.line()
Done

2022-03-11 11:51 UTC, AndreasPB commented on src/haircut_plots.py
> +df_m.groupby("Culture")["Tip amount"].mean().plot.bar(color="orange")
Done

2022-03-11 11:51 UTC, AndreasPB commented
Så skulle det gerne være klar! :see_no_evil:

2022-03-11 12:58 UTC, nullxDEADBEEF reviewed
LGTM

2022-03-11 13:28 UTC, nullxDEADBEEF approved these changes
:shipit:

2022-03-11 13:29 UTC, merged